export const Campaigns: CampaignType[] = [
    {
        id: 1,
        tag: 'purple',
        title: 'Presidents Day ***',
        createdBy: 'Sales360',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'scheduled',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 0,
    },
    {
        id: 2,
        tag: 'red',
        title: 'Essence Maserati Alfa Romeo',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'error',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 15.8,
    },
    {
        id: 3,
        tag: 'gray',
        title: 'Riverfront CD JR ***',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'running',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 123.46,
    },
    {
        id: 4,
        tag: 'green',
        title: 'TaxRefund',
        createdBy: 'Martin Cadillac of Los Angeles',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'running',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 169.88,
    },
    {
        id: 5,
        tag: 'yellow',
        title: 'A World Of Infinite Opportunities',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'error',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 231.61,
    },
    {
        id: 6,
        tag: 'gray',
        title: 'Riverfront CDJR ***',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'running',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 293.34,
    },
    {
        id: 7,
        tag: 'gray',
        title: 'Riverfront CDJR ***',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'scheduled',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 355.07,
    },
    {
        id: 8,
        tag: 'gray',
        title: 'Riverfront CDJR ***',
        createdBy: 'Ray Brandt Dodge',
        fromDate: '04/15/2024',
        toDate: '06/30/2024',
        status: 'running',
        recipients: 7102,
        results: 543,
        leads: 32,
        amountSpent: 416.8,
    },
]
