/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CampaignsLazyImport = createFileRoute('/campaigns')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CampaignsLazyRoute = CampaignsLazyImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/campaigns.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/campaigns': typeof CampaignsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/campaigns': typeof CampaignsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/campaigns': typeof CampaignsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campaigns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaigns'
  id: '__root__' | '/' | '/campaigns'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CampaignsLazyRoute: typeof CampaignsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CampaignsLazyRoute: CampaignsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/campaigns"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/campaigns": {
      "filePath": "campaigns.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
